[build]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy: default-src 'self'; frame-ancestors 'none'
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=31536000,
      immutable'''

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=180"

[[edge_functions]]
  path = "/*"
  function = "strip-non-html-headers"
